env: "HalfCheetah"
policy: "medium_expert"
dataset_group: "D4RL"
dataset_entry: ${datasets.dataset_group}/${datasets.env}/${datasets.env}_${datasets.policy}-v2
env_entry: 'halfcheetah-medium-expert-v2'
